# This file defines the triggers for your AutoPR workflows.
# For more information, see the Triggers reference in the AutoPR documentation.

triggers:
  - type: label
    label_substring: "summarize"
    on_pull_request: true
    run: summarize_and_comment

  - type: push
    branch: main
    run: pr_quality_gate

  - type: comment
    body_substring: "/scaffold"
    on_issue: true
    run: scaffold_and_barrel

  - type: schedule
    cron: "0 9 * * 1" # Every Monday at 9 AM
    run: weekly_tech_debt_report

  - type: tag
    run: draft_release

  - type: comment
    body_substring: "/magic-fix"
    on_pull_request: true
    run: magic_fix

  - type: assign
    on_issue: true
    run: onboard_contributor

  - type: comment
    body_substring: "/update-dep"
    on_pull_request: true
    run: automated_dependency_update

  - type: schedule
    cron: "0 0 * * *" # Daily
    run: stale_issue_closer

  - type: schedule
    cron: "0 8 * * 1" # Weekly
    run: dead_code_report

  - type: schedule
    cron: "0 2 * * *" # Daily security audit
    run: security_audit

  - type: tag
    run: changelog_updater

  - type: schedule
    cron: "0 3 1 * *" # Monthly branch cleanup
    run: branch_cleanup

  - type: pull_request
    run: pr_size_labeler

  - type: push
    branch: main
    run: screenshot_gallery
