# This workflow summarizes the changes in a pull request and posts the summary as a comment.

summarize_and_comment:
  main: summarize_and_comment
  inputs:
    - pull_request
  steps:
    - id: summarize
      action: summarize_pr_with_ai
      outputs:
        summary: comment_text
    - id: post_comment
      action: post_comment
      inputs:
        pull_request_number:
          ref: pull_request.number
        comment:
          var: comment_text
