name: "React TypeScript Configuration"
category: "typescript"
description: "TypeScript configuration optimized for React applications with modern ES features and strict type checking"
version: "1.0.0"
author: "AutoPR Template System"
tags: ["typescript", "react", "configuration", "jsx", "es6"]

template_info:
  name: "React TSConfig"
  type: "typescript_configuration"
  framework: "React"
  target_audience: "React developers, TypeScript developers"
  primary_use_cases: ["React applications", "TypeScript projects", "Create React App", "Modern web development"]

variables:
  target:
    type: "select"
    description: "ECMAScript target version"
    options: ["es5", "es2015", "es2017", "es2018", "es2020", "es2022", "esnext"]
    default: "es5"
    required: false

  strict_mode:
    type: "boolean"
    description: "Enable strict type checking options"
    default: true
    required: false

  jsx_mode:
    type: "select"
    description: "JSX compilation mode"
    options: ["react", "react-jsx", "react-jsxdev", "preserve"]
    default: "react-jsx"
    required: false

  include_paths:
    type: "array"
    description: "Paths to include in compilation"
    default: ["src"]
    required: false

  exclude_paths:
    type: "array"
    description: "Paths to exclude from compilation"
    default: ["node_modules"]
    required: false

  lib_includes:
    type: "array"
    description: "Library files to include"
    default: ["dom", "dom.iterable", "es6"]
    required: false

  module_resolution:
    type: "select"
    description: "Module resolution strategy"
    options: ["node", "classic", "bundler"]
    default: "node"
    required: false

  allow_js:
    type: "boolean"
    description: "Allow JavaScript files to be compiled"
    default: true
    required: false

  source_map:
    type: "boolean"
    description: "Generate source map files"
    default: false
    required: false

  declaration:
    type: "boolean"
    description: "Generate declaration files"
    default: false
    required: false

variants:
  create_react_app:
    description: "Configuration for Create React App projects"
    variables:
      target: "es5"
      jsx_mode: "react-jsx"
      strict_mode: true
      allow_js: true

  modern_react:
    description: "Modern React configuration with latest ES features"
    variables:
      target: "es2020"
      jsx_mode: "react-jsx"
      strict_mode: true
      lib_includes: ["dom", "dom.iterable", "es2020"]

  library_build:
    description: "Configuration for building React libraries"
    variables:
      target: "es2017"
      declaration: true
      source_map: true
      jsx_mode: "react-jsx"

  development:
    description: "Development-friendly configuration"
    variables:
      strict_mode: false
      allow_js: true
      source_map: true

  production:
    description: "Production-optimized configuration"
    variables:
      strict_mode: true
      allow_js: false
      target: "es2017"

usage:
  getting_started:
    - "Place this file as tsconfig.json in your React project root"
    - "Ensure TypeScript is installed in your project"
    - "Configure include/exclude paths for your project structure"
    - "Choose appropriate JSX compilation mode"

  best_practices:
    - "Enable strict mode for better type safety"
    - "Use react-jsx for modern React projects (React 17+)"
    - "Include only necessary library files"
    - "Set appropriate target based on browser support"
    - "Use source maps in development for debugging"
    - "Enable declaration files for library projects"

  limitations:
    - "Some options may conflict with build tools like Webpack"
    - "JSX modes depend on React version compatibility"
    - "Strict mode may require extensive type annotations"
    - "Target version affects available language features"

template: |
  {
    "compilerOptions": {
      "target": "{{ target }}",
      "lib": {{ lib_includes | tojson }},
      "allowJs": {{ allow_js | lower }},
      "skipLibCheck": true,
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "strict": {{ strict_mode | lower }},
      "forceConsistentCasingInFileNames": true,
      "noFallthroughCasesInSwitch": true,
      "module": "esnext",
      "moduleResolution": "{{ module_resolution }}",
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "{{ jsx_mode }}"{% if source_map %},
      "sourceMap": true{% endif %}{% if declaration %},
      "declaration": true{% endif %}
    },
    "include": {{ include_paths | tojson }},
    "exclude": {{ exclude_paths | tojson }}
  }
