name: "React TypeScript Configuration"
description: "TypeScript configuration optimized for React applications"
category: "typescript"
platforms: ["replit", "lovable"]
file_extension: "json"

variables:
  target:
    type: "string"
    default: "es5"
    description: "ECMAScript target version"
  jsx_mode:
    type: "string"
    default: "react-jsx"
    description: "JSX compilation mode"
  strict_mode:
    type: "boolean"
    default: true
    description: "Enable strict type checking"

variants:
  modern_target:
    name: "Modern ES2020 Target"
    description: "Uses ES2020 as target for modern browsers"
    modifications:
      - line: 4
        action: "replace"
        content: '        "target": "ES2020",'

  legacy_jsx:
    name: "Legacy JSX Transform"
    description: "Uses legacy JSX transform"
    modifications:
      - line: 16
        action: "replace"
        content: '        "jsx": "react"'

usage:
  - "Create React App projects"
  - "React applications with TypeScript"
  - "Component libraries"

dependencies:
  required: ["typescript", "react", "@types/react"]
  optional: ["@types/react-dom"]

notes:
  - "Includes DOM type definitions"
  - "Enables strict type checking by default"
  - "Configured for modern React JSX transform"
