name: "Vite TypeScript Configuration"
description: "TypeScript configuration optimized for Vite projects"
category: "typescript"
platforms: ["bolt"]
file_extension: "json"

variables:
  target:
    type: "string"
    default: "ES2020"
    description: "ECMAScript target version"
  module_resolution:
    type: "string"
    default: "bundler"
    description: "Module resolution strategy"
  strict_mode:
    type: "boolean"
    default: true
    description: "Enable strict type checking"

variants:
  with_path_mapping:
    name: "With Path Mapping"
    description: "Includes path mapping for cleaner imports"
    modifications:
      - line: 12
        action: "add_after"
        content:
          '        "baseUrl": ".",\n        "paths": {\n          "@/*": ["src/*"]\n        },'

usage:
  - "Vite React projects"
  - "Modern frontend applications"
  - "TypeScript with Vite bundler"

dependencies:
  required: ["typescript", "vite"]
  optional: ["@vitejs/plugin-react"]

notes:
  - "Optimized for Vite's bundler module resolution"
  - "Includes modern ES2020 features"
  - "Configured for React JSX transform"
