name: "Vite TypeScript Configuration"
category: "typescript"
description:
  "TypeScript configuration optimized for Vite build tool with modern ES features and bundler module
  resolution"
version: "1.0.0"
author: "AutoPR Template System"
tags: ["typescript", "vite", "configuration", "bundler", "modern"]

template_info:
  name: "Vite TSConfig"
  type: "typescript_configuration"
  framework: "Vite"
  target_audience: "Vite developers, modern frontend developers"
  primary_use_cases: ["Vite projects", "Modern build tooling", "React with Vite", "Vue with Vite"]

variables:
  target:
    type: "select"
    description: "ECMAScript target version"
    options: ["ES2015", "ES2017", "ES2018", "ES2020", "ES2022", "ESNext"]
    default: "ES2020"
    required: false

  jsx_mode:
    type: "select"
    description: "JSX compilation mode"
    options: ["react", "react-jsx", "react-jsxdev", "preserve"]
    default: "react-jsx"
    required: false

  strict_mode:
    type: "boolean"
    description: "Enable strict type checking options"
    default: true
    required: false

  unused_locals:
    type: "boolean"
    description: "Report errors on unused local variables"
    default: true
    required: false

  unused_parameters:
    type: "boolean"
    description: "Report errors on unused parameters"
    default: true
    required: false

  include_paths:
    type: "array"
    description: "Paths to include in compilation"
    default: ["src"]
    required: false

  lib_includes:
    type: "array"
    description: "Library files to include"
    default: ["ES2020", "DOM", "DOM.Iterable"]
    required: false

  use_define_for_class_fields:
    type: "boolean"
    description: "Use define semantics for class fields"
    default: true
    required: false

  allow_importing_ts_extensions:
    type: "boolean"
    description: "Allow importing TypeScript extensions"
    default: true
    required: false

  node_tsconfig_reference:
    type: "boolean"
    description: "Include reference to tsconfig.node.json"
    default: true
    required: false

variants:
  react_vite:
    description: "Configuration for React projects with Vite"
    variables:
      jsx_mode: "react-jsx"
      target: "ES2020"
      strict_mode: true
      unused_locals: true

  vue_vite:
    description: "Configuration for Vue projects with Vite"
    variables:
      jsx_mode: "preserve"
      target: "ES2020"
      strict_mode: true

  library_build:
    description: "Configuration for building libraries with Vite"
    variables:
      target: "ES2017"
      strict_mode: true
      unused_locals: false
      unused_parameters: false

  development:
    description: "Development-friendly configuration"
    variables:
      strict_mode: false
      unused_locals: false
      unused_parameters: false

  production:
    description: "Production-optimized configuration"
    variables:
      strict_mode: true
      unused_locals: true
      unused_parameters: true
      target: "ES2020"

usage:
  getting_started:
    - "Place this file as tsconfig.json in your Vite project root"
    - "Ensure TypeScript and Vite are installed"
    - "Create tsconfig.node.json for Node.js configuration if needed"
    - "Configure include paths for your project structure"

  best_practices:
    - "Use ES2020 target for modern browser support"
    - "Enable strict mode for better type safety"
    - "Use bundler module resolution for Vite compatibility"
    - "Enable unused variable detection in production"
    - "Use react-jsx for React 17+ projects"
    - "Include DOM types for browser APIs"

  limitations:
    - "Requires Vite-compatible module resolution"
    - "Some options may not work with older TypeScript versions"
    - "Bundler module resolution is specific to modern tools"
    - "Node.js configuration may need separate tsconfig"

template: |
  {
    "compilerOptions": {
      "target": "{{ target }}",
      "useDefineForClassFields": {{ use_define_for_class_fields | lower }},
      "lib": {{ lib_includes | tojson }},
      "module": "ESNext",
      "skipLibCheck": true,
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": {{ allow_importing_ts_extensions | lower }},
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "{{ jsx_mode }}",
      "strict": {{ strict_mode | lower }},
      {% if unused_locals %}
      "noUnusedLocals": true,
      {% endif %}
      {% if unused_parameters %}
      "noUnusedParameters": true,
      {% endif %}
      "noFallthroughCasesInSwitch": true
    },
    "include": {{ include_paths | tojson }}{% if node_tsconfig_reference %},
    "references": [{"path": "./tsconfig.node.json"}]{% endif %}
  }
