name: "Netlify Deployment Configuration"
category: "deployment"
description:
  "Netlify deployment configuration with build settings, redirects, headers, and environment
  variables for SPAs and static sites"
version: "1.0.0"
author: "AutoPR Template System"
tags: ["netlify", "deployment", "spa", "static-site", "redirects", "headers"]

template_info:
  name: "Netlify Config"
  type: "deployment_configuration"
  framework: "React, Vue, Angular, Static"
  target_audience: "Frontend developers, JAMstack developers"
  primary_use_cases:
    ["Static site deployment", "SPA hosting", "JAMstack applications", "Form handling"]

variables:
  build_command:
    type: "string"
    description: "Build command to generate the site"
    default: "npm run build"
    required: true

  publish_directory:
    type: "string"
    description: "Directory containing the built site"
    default: "build"
    required: true

  node_version:
    type: "string"
    description: "Node.js version for build environment"
    default: "18"
    required: false

  spa_routing:
    type: "boolean"
    description: "Enable SPA routing (redirect all routes to index.html)"
    default: true
    required: false

  security_headers:
    type: "boolean"
    description:
      "Enable security headers (X-Frame-Options, X-XSS-Protection, X-Content-Type-Options)"
    default: true
    required: false

  custom_headers:
    type: "object"
    description: "Additional custom headers"
    default: {}
    required: false

  custom_redirects:
    type: "array"
    description: "Custom redirect rules"
    default: []
    required: false

  environment_variables:
    type: "object"
    description: "Build environment variables"
    default: {}
    required: false

  functions_directory:
    type: "string"
    description: "Directory containing Netlify Functions"
    default: ""
    required: false

  edge_functions_directory:
    type: "string"
    description: "Directory containing Netlify Edge Functions"
    default: ""
    required: false

variants:
  react_spa:
    description: "React Single Page Application configuration"
    variables:
      build_command: "npm run build"
      publish_directory: "build"
      spa_routing: true
      security_headers: true

  vue_spa:
    description: "Vue.js Single Page Application configuration"
    variables:
      build_command: "npm run build"
      publish_directory: "dist"
      spa_routing: true
      security_headers: true

  static_site:
    description: "Static website configuration"
    variables:
      build_command: "npm run build"
      publish_directory: "dist"
      spa_routing: false
      security_headers: true

  jamstack:
    description: "JAMstack application with functions"
    variables:
      spa_routing: true
      security_headers: true
      functions_directory: "netlify/functions"

  production:
    description: "Production-optimized configuration"
    variables:
      node_version: "18"
      security_headers: true
      spa_routing: true

usage:
  getting_started:
    - "Place this file as netlify.toml in your project root"
    - "Configure build command and publish directory"
    - "Set up redirects for SPA routing if needed"
    - "Deploy via Netlify CLI or Git integration"

  best_practices:
    - "Use specific Node.js versions for consistent builds"
    - "Enable security headers for production sites"
    - "Configure SPA redirects for client-side routing"
    - "Use environment variables for configuration"
    - "Test redirects and headers in deploy previews"
    - "Monitor build logs for optimization opportunities"

  limitations:
    - "Build time limit varies by plan"
    - "Function execution timeout is 10 seconds (26 seconds for Pro)"
    - "Some advanced features require paid plans"
    - "Environment variables are case-sensitive"

template: |
  [build]
    publish = "{{ publish_directory }}"
    command = "{{ build_command }}"
    {% if functions_directory %}
    functions = "{{ functions_directory }}"
    {% endif %}
    {% if edge_functions_directory %}
    edge_functions = "{{ edge_functions_directory }}"
    {% endif %}

  [build.environment]
    NODE_VERSION = "{{ node_version }}"
    {% for key, value in environment_variables.items() %}
    {{ key }} = "{{ value }}"
    {% endfor %}

  {% if spa_routing or custom_redirects %}
  {% if spa_routing %}
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
  {% endif %}

  {% for redirect in custom_redirects %}
  [[redirects]]
    from = "{{ redirect.from }}"
    to = "{{ redirect.to }}"
    status = {{ redirect.status | default(301) }}
    {% if redirect.force %}
    force = {{ redirect.force | lower }}
    {% endif %}
    {% if redirect.conditions %}
    conditions = {{ redirect.conditions | tojson }}
    {% endif %}
  {% endfor %}
  {% endif %}

  {% if security_headers or custom_headers %}
  [[headers]]
    for = "/*"
    [headers.values]
      {% if security_headers %}
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      {% endif %}
      {% for key, value in custom_headers.items() %}
      {{ key }} = "{{ value }}"
      {% endfor %}
  {% endif %}

  # Cache static assets
  [[headers]]
    for = "/static/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [[headers]]
    for = "*.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [[headers]]
    for = "*.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
