name: "Vercel Deployment Configuration"
category: "deployment"
description: "Vercel deployment configuration for React SPAs, Node.js APIs, and static sites with routing and build optimization"
version: "1.0.0"
author: "AutoPR Template System"
tags: ["vercel", "deployment", "spa", "serverless", "routing", "build"]

template_info:
  name: "Vercel Config"
  type: "deployment_configuration"
  framework: "React, Node.js, Static"
  target_audience: "Frontend developers, full-stack developers"
  primary_use_cases: ["Static site deployment", "SPA hosting", "Serverless functions", "API deployment"]

variables:
  framework:
    type: "select"
    description: "Application framework type"
    options: ["react", "node", "express", "static", "nextjs"]
    default: "react"
    required: true

  spa_routing:
    type: "boolean"
    description: "Enable SPA routing (fallback to index.html)"
    default: true
    required: false

  build_command:
    type: "string"
    description: "Custom build command override"
    default: ""
    required: false

  output_directory:
    type: "string"
    description: "Build output directory"
    default: "build"
    required: false

  node_version:
    type: "string"
    description: "Node.js version for build environment"
    default: "18.x"
    required: false

  environment_variables:
    type: "object"
    description: "Environment variables for build and runtime"
    default: {}
    required: false

  custom_routes:
    type: "array"
    description: "Custom routing rules"
    default: []
    required: false

  headers:
    type: "array"
    description: "Custom headers for responses"
    default: []
    required: false

  redirects:
    type: "array"
    description: "URL redirects configuration"
    default: []
    required: false

variants:
  react_spa:
    description: "React Single Page Application configuration"
    variables:
      framework: "react"
      spa_routing: true
      output_directory: "build"

  node_api:
    description: "Node.js API serverless functions"
    variables:
      framework: "node"
      spa_routing: false

  static_site:
    description: "Static website deployment"
    variables:
      framework: "static"
      spa_routing: false
      output_directory: "dist"

  nextjs_app:
    description: "Next.js application with automatic configuration"
    variables:
      framework: "nextjs"
      spa_routing: false

  production:
    description: "Production-optimized configuration"
    variables:
      node_version: "18.x"
      spa_routing: true

usage:
  getting_started:
    - "Place this file as vercel.json in your project root"
    - "Choose the appropriate variant for your application type"
    - "Configure custom routes and headers as needed"
    - "Deploy using Vercel CLI or GitHub integration"

  best_practices:
    - "Use specific Node.js versions for consistent builds"
    - "Enable SPA routing for client-side routing applications"
    - "Set appropriate cache headers for static assets"
    - "Use environment variables for configuration"
    - "Test routing configuration in preview deployments"
    - "Monitor build logs for optimization opportunities"

  limitations:
    - "Build time limit of 45 minutes on Hobby plan"
    - "Function execution timeout varies by plan"
    - "Some advanced routing features require Pro plan"
    - "Environment variables are case-sensitive"

template: |
  {
    "version": 2,
    {% if build_command %}
    "buildCommand": "{{ build_command }}",
    {% endif %}
    {% if output_directory %}
    "outputDirectory": "{{ output_directory }}",
    {% endif %}
    "builds": [
      {
        "src": "package.json",
        "use": "{% if framework in ['node', 'express'] %}@vercel/node{% elif framework == 'nextjs' %}@vercel/next{% else %}@vercel/static-build{% endif %}"
      }
    ],
    {% if environment_variables %}
    "env": {{ environment_variables | tojson }},
    {% endif %}
    {% if spa_routing or custom_routes %}
    "routes": [
      {% if spa_routing and framework == 'react' %}
      {"handle": "filesystem"},
      {"src": "/.*", "dest": "/index.html"}
      {% endif %}
      {% for route in custom_routes %}
      {% if not loop.first or spa_routing %},{% endif %}
      {
        "src": "{{ route.src }}",
        "dest": "{{ route.dest }}"
        {% if route.status %},
        "status": {{ route.status }}
        {% endif %}
        {% if route.headers %},
        "headers": {{ route.headers | tojson }}
        {% endif %}
      }
      {% endfor %}
    ],
    {% endif %}
    {% if headers %}
    "headers": [
      {% for header in headers %}
      {
        "source": "{{ header.source }}",
        "headers": {{ header.headers | tojson }}
      }{% if not loop.last %},{% endif %}
      {% endfor %}
    ],
    {% endif %}
    {% if redirects %}
    "redirects": [
      {% for redirect in redirects %}
      {
        "source": "{{ redirect.source }}",
        "destination": "{{ redirect.destination }}"
        {% if redirect.permanent %},
        "permanent": {{ redirect.permanent | lower }}
        {% endif %}
      }{% if not loop.last %},{% endif %}
      {% endfor %}
    ]
    {% endif %}
  }
