name: "Azure App Service Web.config"
category: "deployment"
description:
  "Azure App Service web.config for React SPA and Node.js applications with URL rewriting and
  security headers"
version: "1.0.0"
author: "AutoPR Template System"
tags: ["azure", "app-service", "web.config", "deployment", "security", "spa"]

template_info:
  name: "Azure Web.config"
  type: "deployment_configuration"
  framework: "React, Node.js"
  target_audience: "Azure developers, DevOps engineers"
  primary_use_cases:
    ["Azure App Service deployment", "SPA routing", "Node.js hosting", "Security headers"]

variables:
  framework:
    type: "select"
    description: "Application framework type"
    options: ["react", "node", "static"]
    default: "react"
    required: true

  enable_security_headers:
    type: "boolean"
    description:
      "Enable security headers (X-Content-Type-Options, X-Frame-Options, X-XSS-Protection)"
    default: true
    required: false

  spa_routing:
    type: "boolean"
    description: "Enable SPA routing (redirect all routes to index.html)"
    default: true
    required: false

  node_entry_point:
    type: "string"
    description: "Node.js application entry point file"
    default: "index.js"
    required: false

  custom_headers:
    type: "array"
    description: "Additional custom HTTP headers"
    default: []
    required: false

  compression:
    type: "boolean"
    description: "Enable static compression for better performance"
    default: true
    required: false

  cache_control:
    type: "boolean"
    description: "Enable cache control headers for static assets"
    default: true
    required: false

variants:
  react_spa:
    description: "Configuration for React Single Page Applications"
    variables:
      framework: "react"
      spa_routing: true
      enable_security_headers: true
      compression: true

  node_api:
    description: "Configuration for Node.js API applications"
    variables:
      framework: "node"
      spa_routing: false
      node_entry_point: "index.js"
      enable_security_headers: true

  static_site:
    description: "Configuration for static websites"
    variables:
      framework: "static"
      spa_routing: false
      enable_security_headers: true
      compression: true
      cache_control: true

  production:
    description: "Production-optimized configuration with all security features"
    variables:
      enable_security_headers: true
      compression: true
      cache_control: true

usage:
  getting_started:
    - "Place this file as web.config in your application root directory"
    - "Choose the appropriate variant for your application type"
    - "Customize security headers and caching as needed"
    - "Deploy to Azure App Service"

  best_practices:
    - "Always enable security headers in production"
    - "Use SPA routing for React applications"
    - "Enable compression for better performance"
    - "Set appropriate cache control headers for static assets"
    - "Test routing configuration thoroughly"
    - "Monitor application logs for rewrite rule issues"

  limitations:
    - "Only works with Azure App Service (Windows)"
    - "IIS-specific configuration syntax"
    - "Some features may not work with Linux App Service"
    - "Complex routing rules may impact performance"

template: |
  <?xml version="1.0" encoding="utf-8"?>
  <configuration>
    <system.webServer>
      {% if framework == "node" %}
      <handlers>
        <add name="iisnode" path="{{ node_entry_point }}" verb="*" modules="iisnode"/>
      </handlers>
      {% endif %}

      {% if spa_routing or framework == "node" %}
      <rewrite>
        <rules>
          {% if framework == "react" and spa_routing %}
          <rule name="React Routes" stopProcessing="true">
            <match url=".*" />
            <conditions logicalGrouping="MatchAll">
              <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
              <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            </conditions>
            <action type="Rewrite" url="/" />
          </rule>
          {% elif framework == "node" %}
          <rule name="DynamicContent">
            <match url="/*" />
            <action type="Rewrite" url="{{ node_entry_point }}"/>
          </rule>
          {% endif %}
        </rules>
      </rewrite>
      {% endif %}

      {% if enable_security_headers or custom_headers or cache_control %}
      <httpHeaders>
        {% if enable_security_headers %}
        <add name="X-Content-Type-Options" value="nosniff" />
        <add name="X-Frame-Options" value="DENY" />
        <add name="X-XSS-Protection" value="1; mode=block" />
        <add name="Referrer-Policy" value="strict-origin-when-cross-origin" />
        {% endif %}

        {% if cache_control %}
        <add name="Cache-Control" value="public, max-age=31536000" />
        {% endif %}

        {% for header in custom_headers %}
        <add name="{{ header.name }}" value="{{ header.value }}" />
        {% endfor %}
      </httpHeaders>
      {% endif %}

      {% if compression %}
      <urlCompression doStaticCompression="true" doDynamicCompression="true" />
      <staticContent>
        <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" />
        <mimeMap fileExtension=".json" mimeType="application/json" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
        <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
      </staticContent>
      {% endif %}

      {% if framework == "node" %}
      <iisnode nodeProcessCommandLine="node.exe" />
      {% endif %}
    </system.webServer>
  </configuration>
