name: "Jest Testing Configuration"
description: "Jest configuration for React applications with coverage reporting"
category: "testing"
platforms: ["replit", "lovable", "bolt"]
file_extension: "js"

variables:
  test_environment:
    type: "string"
    default: "jsdom"
    description: "Testing environment (jsdom for React, node for backend)"
  coverage_threshold:
    type: "number"
    default: 80
    description: "Minimum coverage percentage required"
  setup_file:
    type: "string"
    default: "<rootDir>/src/setupTests.ts"
    description: "Path to test setup file"

variants:
  with_typescript:
    name: "With TypeScript Support"
    description: "Includes TypeScript transformation"
    modifications:
      - line: 2
        action: "add_after"
        content: "  preset: 'ts-jest',"

  backend_testing:
    name: "Backend/Node Testing"
    description: "Configured for Node.js backend testing"
    modifications:
      - line: 2
        action: "replace"
        content: "  testEnvironment: 'node',"

usage:
  - "React component testing"
  - "Unit testing with coverage"
  - "Integration testing"

dependencies:
  required: ["jest", "@testing-library/react", "@testing-library/jest-dom"]
  optional: ["@testing-library/user-event", "ts-jest"]

notes:
  - "Includes CSS module mocking"
  - "Configured for 80% coverage threshold"
  - "Excludes index and reportWebVitals from coverage"
