# autopr/workflows/automated_dependency_update.yaml
automated_dependency_update:
  main: automated_dependency_update
  inputs:
    - package_name
  steps:
    - id: update_dep
      action: update_dependency
      inputs:
        package_name:
          var: package_name
    - id: run_tests
      action: run_changed_tests
    - id: post_comment
      action: post_comment
      inputs:
        pull_request_number: "{{ pull_request.number }}"
        comment: |
          📦 Dependency `{{ package_name }}` was updated and tests were run. See logs for details.
