# autopr/workflows/branch_cleanup.yaml
branch_cleanup:
  main: branch_cleanup
  steps:
    - id: find_branches
      action: find_merged_branches
      outputs:
        merged_branches: branches_to_delete
    - id: delete_branches
      # This would need a loop in a real workflow engine.
      # For simulation, we'll just delete the first one.
      action: delete_branch
      inputs:
        branch_name: '{{ branches_to_delete[0] }}'
