# autopr/workflows/changelog_updater.yaml
changelog_updater:
  main: changelog_updater
  inputs:
    - tag_name
  steps:
    - id: get_notes
      action: generate_release_notes
      inputs:
        from_tag: '{{ tag_name }}'
      outputs:
        release_notes: notes
    - id: update_changelog
      action: update_docs_file
      inputs:
        filepath: 'CHANGELOG.md'
        content: '{{ notes }}'
        start_marker: '<!-- CHANGELOG:START -->'
        end_marker: '<!-- CHANGELOG:END -->'
