# autopr/workflows/dead_code_report.yaml
dead_code_report:
  main: dead_code_report
  steps:
    - id: find_dead
      action: find_dead_code
      outputs:
        dead_code_report: report
    - id: post_report
      action: post_comment
      inputs:
        pull_request_number: 1 # For demo, post to PR #1
        comment: |
          🧹 Dead code report:
          {{ report }}
