# autopr/workflows/magic_fix.yaml
magic_fix:
  main: magic_fix
  inputs:
    - pull_request
  steps:
    - id: run_tests
      action: run_changed_tests
    - id: lint_imports
      action: enforce_import_order
    - id: apply_patch
      action: apply_git_patch
      inputs:
        patch_content: '{{ pull_request.patch }}' # Simulated; in real use, would generate a patch
