# autopr/workflows/onboard_contributor.yaml
onboard_contributor:
  main: onboard_contributor
  inputs:
    - issue
  steps:
    - id: welcome_comment
      action: post_comment
      inputs:
        pull_request_number: "{{ issue.number }}"
        comment: |
          👋 Welcome to the project!
          Please see our [CONTRIBUTING.md](../CONTRIBUTING.md) and [README.md](../README.md) for guidelines and tips.
          If you have any questions, feel free to ask!
