name: "Phase 2: Rapid Prototyping to Production"
description: "Automated workflow for converting rapid prototypes to production-ready applications"

triggers:
  - on: push
    branches: [main, develop]
    condition: "contains(github.event.head_commit.message, 'replit') || contains(github.event.head_commit.message, 'lovable') || contains(github.event.head_commit.message, 'bolt') || contains(github.event.head_commit.message, 'same') || contains(github.event.head_commit.message, 'emergent')"
  
  - on: repository_dispatch
    event_types: [prototype-export, replit-export, lovable-export, bolt-export]
  
  - on: workflow_dispatch
    inputs:
      platform_override:
        description: "Override platform detection"
        required: false
        type: choice
        options: ["auto-detect", "replit", "lovable", "bolt", "same", "emergent"]
      
      enhancement_level:
        description: "Enhancement level"
        required: true
        type: choice
        options: ["basic", "production_ready", "enterprise"]
        default: "production_ready"

inputs:
  enhance_for_production:
    type: boolean
    default: true
    description: "Automatically enhance prototype for production"
  
  target_platform:
    type: string
    default: "azure"
    description: "Target deployment platform"
  
  enable_monitoring:
    type: boolean
    default: true
    description: "Enable Azure SRE monitoring"
  
  create_staging:
    type: boolean
    default: true
    description: "Create staging environment"
  
  run_e2e_tests:
    type: boolean
    default: true
    description: "Run end-to-end tests"
