name: "PR Comment Handler"
description:
  "Automatically processes PR comments, attempts fixes, and creates issues for complex feedback"

triggers:
  - on: pr_comment_created
  - on: pr_review_comment_created

steps:
  - name: "extract_comment_info"
    action: "extract_pr_comment_data"
    inputs:
      comment_id: "{{ event.comment.id }}"
      pr_number: "{{ event.pull_request.number }}"
    outputs:
      comment_body: "{{ comment.body }}"
      comment_author: "{{ comment.user.login }}"
      repo_owner: "{{ repository.owner.login }}"
      repo_name: "{{ repository.name }}"
      branch_name: "{{ event.pull_request.head.ref }}"
      file_path: "{{ comment.path | default('') }}"
      line_number: "{{ comment.line | default(0) }}"

  - name: "handle_comment"
    action: "handle_pr_comment"
    inputs:
      comment_body: "{{ steps.extract_comment_info.outputs.comment_body }}"
      comment_author: "{{ steps.extract_comment_info.outputs.comment_author }}"
      pr_number: "{{ steps.extract_comment_info.outputs.pr_number }}"
      comment_id: "{{ steps.extract_comment_info.outputs.comment_id }}"
      repo_owner: "{{ steps.extract_comment_info.outputs.repo_owner }}"
      repo_name: "{{ steps.extract_comment_info.outputs.repo_name }}"
      branch_name: "{{ steps.extract_comment_info.outputs.branch_name }}"
      file_path: "{{ steps.extract_comment_info.outputs.file_path }}"
      line_number: "{{ steps.extract_comment_info.outputs.line_number }}"

  - name: "commit_fixes"
    action: "git_commit_and_push"
    inputs:
      branch_name: "{{ steps.extract_comment_info.outputs.branch_name }}"
      commit_message: "🤖 AutoPR: {{ steps.handle_comment.outputs.response_message }}"
    when: "{{ steps.handle_comment.outputs.fix_applied == true }}"

  - name: "post_response"
    action: "post_comment"
    inputs:
      pr_number: "{{ steps.extract_comment_info.outputs.pr_number }}"
      comment_body: |
        🤖 **AutoPR Response:**

        {{ steps.handle_comment.outputs.response_message }}

        {% if steps.handle_comment.outputs.issue_created %}
        📝 Created issue #{{ steps.handle_comment.outputs.issue_number }} to track this feedback.
        {% endif %}

        {% if steps.handle_comment.outputs.fix_applied %}
        ✅ Fix has been applied and committed to this PR.
        {% endif %}
    when: "{{ steps.handle_comment.outputs.action_taken != 'acknowledged' }}"

conditions:
  # Only process comments that look like actionable feedback
  - comment_contains_keywords:
      - "fix"
      - "change"
      - "update"
      - "remove"
      - "add"
      - "typo"
      - "bug"
      - "issue"
      - "problem"
      - "improve"
      - "refactor"
      - "optimize"

  # Don't process comments from bots
  - not_from_bot: true

  # Only process comments on open PRs
  - pr_state: "open"
