# autopr/workflows/pr_size_labeler.yaml
pr_size_labeler:
  main: pr_size_labeler
  inputs:
    - pull_request
  steps:
    - id: get_size
      action: label_pr_by_size
      outputs:
        size_label: label
    - id: apply_label
      # In a real workflow, this would use a GitHub API action to apply the label.
      action: post_comment
      inputs:
        pull_request_number: "{{ pull_request.number }}"
        comment: "Applying size label: `{{ label }}` (simulated)"
