# autopr/workflows/quality_gate.yaml
pr_quality_gate:
  main: pr_quality_gate
  inputs:
    - pull_request
  steps:
    - id: label
      action: label_pr
    - id: lockfile_check
      action: check_lockfile_drift
    - id: console_log_check
      action: analyze_console_logs
    - id: run_tests
      action: run_changed_tests
    - id: license_check
      action: check_dependency_licenses
    # The outputs of these actions could be used to post a summary comment.
