# autopr/workflows/screenshot_gallery.yaml
screenshot_gallery:
  main: screenshot_gallery
  steps:
    - id: take_screenshots
      action: take_screenshots
      inputs:
        urls: ["/", "/about", "/pricing"]
      outputs:
        screenshot_paths: paths
    - id: update_gallery_doc
      action: update_docs_file
      inputs:
        filepath: "docs/screenshot-gallery.md"
        content: |
          # Screenshot Gallery
          {% for path in paths %}
          ![Screenshot]({{ path }})
          {% endfor %}
