# autopr/workflows/stale_issue_closer.yaml
stale_issue_closer:
  main: stale_issue_closer
  steps:
    - id: find_stale
      action: find_stale_issues_or_prs
      inputs:
        days_stale: 30
        type: "issue"
      outputs:
        stale_items: stale_issues
    - id: comment_on_stale
      action: post_comment
      inputs:
        pull_request_number: "{{ stale_issues[0].number }}" # For demo, just the first
        comment: |
          ⚠️ This issue has been marked as stale due to inactivity. Please update or comment to keep it open.
