# autopr/workflows/update_documentation.yaml
update_component_docs:
  main: update_component_docs
  inputs:
    - component_path
    - docs_path
  steps:
    - id: get_props
      action: generate_prop_table
      inputs:
        component_path:
          var: component_path
      outputs:
        markdown_table: table_content
    - id: update_docs
      action: update_docs_file
      inputs:
        filepath:
          var: docs_path
        content:
          var: table_content
