# Development Environment Configuration
# This file contains settings specific to the development environment

# Enable debug mode and verbose logging
debug: true

# Monitoring settings for development
monitoring:
  log_level: "DEBUG"
  structured_logging: true
  enable_metrics: true
  enable_tracing: false

# Workflow settings optimized for development
workflow:
  max_concurrent: 5
  timeout: 600  # 10 minutes for debugging
  retry_attempts: 1  # Fail fast in development
  enable_parallel_execution: false  # Easier debugging

# Database settings for development
database:
  echo: true  # Log SQL queries
  pool_size: 5
  max_overflow: 10

# Redis settings for development
redis:
  host: "localhost"
  port: 6379
  db: 0

# Security settings (relaxed for development)
security:
  enable_cors: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8000"
  enable_csrf_protection: false
  rate_limit_per_minute: 1000  # High limit for development

# LLM settings for development
llm:
  max_tokens: 2000  # Lower for cost efficiency
  temperature: 0.3  # More deterministic for testing
  timeout: 30
  max_retries: 2

# GitHub settings for development
github:
  timeout: 10
  max_retries: 2

# Custom development settings
custom:
  enable_hot_reload: true
  mock_external_apis: false
  log_api_requests: true
  enable_profiling: true
