# Production Environment Configuration
# This file contains settings specific to the production environment

# Disable debug mode
debug: false

# Monitoring settings for production
monitoring:
  log_level: "INFO"
  structured_logging: true
  enable_metrics: true
  enable_tracing: true
  metrics_port: 8000

# Workflow settings optimized for production
workflow:
  max_concurrent: 20 # Higher concurrency for production load
  timeout: 300 # 5 minutes
  retry_attempts: 3
  retry_delay: 10
  enable_parallel_execution: true

# Database settings for production
database:
  echo: false # Don't log SQL in production
  pool_size: 20
  max_overflow: 40
  pool_timeout: 60
  pool_recycle: 3600

# Redis settings for production
redis:
  ssl: true # Enable SSL in production
  timeout: 10
  max_connections: 100

# Security settings (strict for production)
security:
  enable_cors: true
  allowed_origins: [] # Must be explicitly configured
  enable_csrf_protection: true
  rate_limit_per_minute: 60
  jwt_expiry: 1800 # 30 minutes

# LLM settings for production
llm:
  max_tokens: 4000
  temperature: 0.7
  timeout: 60
  max_retries: 3

# GitHub settings for production
github:
  timeout: 30
  max_retries: 3

# Custom production settings
custom:
  enable_hot_reload: false
  mock_external_apis: false
  log_api_requests: false
  enable_profiling: false
  enable_health_checks: true
  enable_graceful_shutdown: true
