# Staging Environment Configuration
# This file contains settings specific to the staging environment

# Disable debug mode but enable detailed logging
debug: false

# Monitoring settings for staging
monitoring:
  log_level: "DEBUG" # More verbose logging for staging
  structured_logging: true
  enable_metrics: true
  enable_tracing: true
  metrics_port: 8000

# Workflow settings optimized for staging
workflow:
  max_concurrent: 10 # Moderate concurrency for staging
  timeout: 300 # 5 minutes
  retry_attempts: 2
  retry_delay: 5
  enable_parallel_execution: true

# Database settings for staging
database:
  echo: false
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 1800

# Redis settings for staging
redis:
  ssl: false # May not have SSL in staging
  timeout: 5
  max_connections: 50

# Security settings (moderate for staging)
security:
  enable_cors: true
  allowed_origins:
    - "https://staging.autopr.dev"
    - "https://staging-api.autopr.dev"
  enable_csrf_protection: true
  rate_limit_per_minute: 120
  jwt_expiry: 3600 # 1 hour

# LLM settings for staging
llm:
  max_tokens: 3000
  temperature: 0.5
  timeout: 45
  max_retries: 2

# GitHub settings for staging
github:
  timeout: 20
  max_retries: 2

# Custom staging settings
custom:
  enable_hot_reload: false
  mock_external_apis: false
  log_api_requests: true
  enable_profiling: true
  enable_health_checks: true
  enable_performance_monitoring: true
