# Testing Environment Configuration
# This file contains settings specific to the testing environment

# Disable debug mode but keep detailed logging
debug: false

# Monitoring settings for testing
monitoring:
  log_level: "INFO"
  structured_logging: true
  enable_metrics: false  # Disable metrics collection in tests
  enable_tracing: false

# Workflow settings optimized for testing
workflow:
  max_concurrent: 1  # Sequential execution for predictable tests
  timeout: 30  # Short timeout for fast test execution
  retry_attempts: 0  # No retries in tests
  enable_parallel_execution: false

# Database settings for testing (use in-memory or test DB)
database:
  echo: false  # Don't log SQL in tests
  pool_size: 1
  max_overflow: 0
  url: "sqlite:///:memory:"  # In-memory database for tests

# Redis settings for testing (use fake Redis)
redis:
  host: "localhost"
  port: 6379
  db: 15  # Use separate DB for tests

# Security settings (minimal for testing)
security:
  enable_cors: true
  allowed_origins: ["*"]
  enable_csrf_protection: false
  rate_limit_per_minute: 10000  # No rate limiting in tests

# LLM settings for testing (use mocks)
llm:
  max_tokens: 100  # Small for fast tests
  temperature: 0.0  # Deterministic for reproducible tests
  timeout: 5
  max_retries: 0

# GitHub settings for testing
github:
  timeout: 5
  max_retries: 0

# Custom testing settings
custom:
  mock_external_apis: true
  use_fake_responses: true
  enable_test_fixtures: true
  fast_mode: true
