version: '3.8'

services:
  autopr-engine:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    volumes:
      - ..:/workspace:cached
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
    environment:
      - AUTOPR_DEBUG=true
      - AUTOPR_LOG_LEVEL=DEBUG
      - PYTHONPATH=/workspace
    command: sleep infinity
    ports:
      - '8080:8080'
      - '5678:5678' # debugpy port
    depends_on:
      - postgres
      - redis

  postgres:
    environment:
      - POSTGRES_DB=autopr_dev
      - POSTGRES_USER=autopr_dev
      - POSTGRES_PASSWORD=autopr_dev_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d

  redis:
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data

volumes:
  vscode-extensions:
  vscode-extensions-insiders:
  postgres_dev_data:
  redis_dev_data:
