# AutoPR Configuration
# Configuration for all tools and workflows

quality_engine:
  default_mode: "smart"
  max_concurrent_fixes: 5
  timeout_seconds: 300

  linting:
    tools:
      ruff:
        enabled: true
        config: "pyproject.toml"
        fix_safe: true
      flake8:
        enabled: true
        max_line_length: 100
      black:
        enabled: true
        line_length: 100

    fix_types:
      high_priority: ["F401", "F841", "E501", "E722"]
      medium_priority: ["E302", "E305", "D200", "D205"]
      low_priority: ["FURB110", "PERF401"]

  ai_agents:
    provider: "azure_openai"
    model: "gpt-4.1"
    max_workers: 2
    specialized_agents:
      - "code_reviewer"
      - "style_fixer"
      - "documentation_generator"

  platforms:
    github:
      enabled: true
      auto_pr: true
    linear:
      enabled: false
    slack:
      enabled: false
    discord:
      enabled: false

templates:
  discovery:
    enabled: true
    auto_detect: true
    confidence_threshold: 0.8

  generation:
    output_dir: "generated"
    backup_existing: true

workflows:
  pre_commit:
    stages: ["format", "lint", "ai_fix"]
    fail_fast: false

  ci_cd:
    stages: ["test", "quality_check", "deploy"]
    parallel_execution: true

monitoring:
  metrics_enabled: true
  logging_level: "INFO"
  performance_tracking: true
